const fs = require('fs');
const path = require('path');

let testResults = { passed: 0, failed: 0, tests: [] };

function addTestResult(name, passed, message) {
  testResults.tests.push({ name, passed, message });
  if (passed) {
    testResults.passed++;
    console.log(`✅ ${name}: ${message}`);
  } else {
    testResults.failed++;
    console.error(`❌ ${name}: ${message}`);
  }
}

async function runTests() {
  console.log('🧪 상품정보 대본 → YouTube 설명란 연동 테스트\n');

  const uploadPath = path.join(__dirname, 'trend-video-frontend', 'src', 'app', 'api', 'youtube', 'upload', 'route.ts');
  const uploadContent = fs.readFileSync(uploadPath, 'utf-8');

  // 테스트 1: 상품정보 대본 찾기 로직 존재
  const hasProductInfoQuery = uploadContent.includes('SELECT content FROM scripts') &&
                               uploadContent.includes('상품 기입 정보') &&
                               uploadContent.includes('product-info');
  addTestResult('상품정보 대본 조회 로직', hasProductInfoQuery,
    hasProductInfoQuery ? 'DB 쿼리 존재' : 'DB 쿼리 누락');

  // 테스트 2: title 패턴 매칭
  const hasTitlePattern = uploadContent.includes('title LIKE ?') &&
                          uploadContent.includes('%${job.title}%상품 기입 정보%');
  addTestResult('title 패턴 매칭', hasTitlePattern,
    hasTitlePattern ? '"{제목} - 상품 기입 정보" 패턴 매칭' : '패턴 매칭 누락');

  // 테스트 3: user_id 필터링
  const hasUserFilter = uploadContent.includes('WHERE user_id = ?') ||
                        uploadContent.includes('user_id = ?');
  addTestResult('user_id 필터링', hasUserFilter,
    hasUserFilter ? '같은 사용자의 스크립트만 검색' : '필터링 누락');

  // 테스트 4: 최신순 정렬
  const hasOrderBy = uploadContent.includes('ORDER BY created_at DESC');
  addTestResult('최신순 정렬', hasOrderBy,
    hasOrderBy ? '가장 최근 상품정보 대본 사용' : '정렬 누락');

  // 테스트 5: autoGeneratedDescription에 할당
  const assignsToAutoDesc = uploadContent.includes('autoGeneratedDescription = productInfoScript.content');
  addTestResult('description 할당', assignsToAutoDesc,
    assignsToAutoDesc ? 'productInfoScript.content → autoGeneratedDescription' : '할당 누락');

  // 테스트 6: 에러 처리
  const hasErrorHandling = uploadContent.includes('catch (dbError)') &&
                           uploadContent.includes('상품정보 대본 로드 실패');
  addTestResult('에러 처리', hasErrorHandling,
    hasErrorHandling ? 'DB 에러 처리 로직 존재' : '에러 처리 누락');

  // 테스트 7: 대체 설명 (fallback)
  const hasFallback = uploadContent.includes('상품정보 대본을 찾을 수 없음') &&
                      uploadContent.includes('기본 설명 사용');
  addTestResult('대체 설명 (fallback)', hasFallback,
    hasFallback ? '상품정보 없을 때 기본 설명 사용' : 'fallback 누락');

  // 테스트 8: DB connection close
  const hasDbClose = uploadContent.includes('db.close()');
  addTestResult('DB connection close', hasDbClose,
    hasDbClose ? 'DB 연결 정리' : 'close() 누락 (메모리 누수 위험)');

  // 결과 요약
  console.log('\n' + '='.repeat(60));
  console.log(`✅ 통과: ${testResults.passed}/${testResults.tests.length}`);
  console.log(`❌ 실패: ${testResults.failed}/${testResults.tests.length}`);
  console.log('='.repeat(60));

  if (testResults.failed > 0) {
    console.log('\n🔍 실패한 테스트:');
    testResults.tests.filter(t => !t.passed).forEach(t => {
      console.log(`  - ${t.name}: ${t.message}`);
    });
  } else {
    console.log('\n✅ 모든 테스트 통과!');
    console.log('\n📋 구현된 기능:');
    console.log('  1. job.type === "product"일 때 상품정보 대본 검색');
    console.log('  2. 검색 조건:');
    console.log('     - 같은 user_id');
    console.log('     - title에 job.title 포함');
    console.log('     - title에 "상품 기입 정보" 또는 "product-info" 포함');
    console.log('  3. 최신 상품정보 대본 사용 (ORDER BY created_at DESC)');
    console.log('  4. content를 YouTube description에 설정');
    console.log('  5. 못 찾으면 기본 설명 사용');
    console.log('\n💡 상품정보 대본이 포함해야 할 내용:');
    console.log('  - 상품명');
    console.log('  - 쿠팡 딥링크 (파트너스 링크)');
    console.log('  - 상품 설명/특징');
    console.log('  - 구매 안내');
    console.log('\n⚠️ 주의사항:');
    console.log('  - 상품정보 대본이 미리 생성되어 있어야 함');
    console.log('  - 대본 제목 형식: "{상품명} - 상품 기입 정보"');
  }

  process.exit(testResults.failed === 0 ? 0 : 1);
}

runTests().catch(error => {
  console.error('❌ 테스트 실행 오류:', error);
  process.exit(1);
});
