"""
Douyin 쿠키 추출 헬퍼
Selenium으로 브라우저를 열고 사용자가 로그인하면 자동으로 쿠키를 저장합니다.
"""
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from webdriver_manager.chrome import ChromeDriverManager
import time
from pathlib import Path
import json


def extract_douyin_cookies(output_file: Path):
    """
    Douyin 쿠키 추출

    Args:
        output_file: 쿠키를 저장할 파일 경로
    """
    print("=" * 80)
    print("🍪 Douyin 쿠키 추출 헬퍼")
    print("=" * 80)
    print()
    print("✋ 잠시 후 브라우저가 열립니다.")
    print("📝 Douyin(抖音) 사이트에서 로그인해주세요.")
    print("⏰ 로그인 후 30초 대기 후 자동으로 쿠키를 저장합니다.")
    print()

    # Chrome 옵션 설정
    chrome_options = Options()
    chrome_options.add_argument('--disable-blink-features=AutomationControlled')
    chrome_options.add_experimental_option("excludeSwitches", ["enable-automation"])
    chrome_options.add_experimental_option('useAutomationExtension', False)

    # Chrome 드라이버 시작
    print("🚀 Chrome 브라우저 시작 중...")
    driver = webdriver.Chrome(
        service=Service(ChromeDriverManager().install()),
        options=chrome_options
    )

    try:
        # Douyin 열기
        print("🌐 Douyin 사이트 접속 중: https://www.douyin.com")
        driver.get("https://www.douyin.com")

        print()
        print("=" * 80)
        print("⏳ 지금 브라우저에서 로그인해주세요!")
        print("=" * 80)
        print()
        print("📱 로그인 방법:")
        print("  1. QR 코드 스캔으로 로그인")
        print("  2. 또는 전화번호/이메일로 로그인")
        print()
        print("⏰ 로그인 후 30초 동안 대기합니다...")
        print()

        # 30초 대기 (사용자가 로그인할 시간)
        for i in range(30, 0, -1):
            print(f"\r⏳ 남은 시간: {i}초...", end="", flush=True)
            time.sleep(1)

        print("\n")
        print("=" * 80)
        print("🍪 쿠키 추출 중...")
        print("=" * 80)
        print()

        # 쿠키 가져오기
        cookies = driver.get_cookies()

        if not cookies:
            print("❌ 쿠키를 찾을 수 없습니다. 로그인이 제대로 되지 않았을 수 있습니다.")
            return False

        # Netscape 쿠키 형식으로 변환 (yt-dlp가 사용하는 형식)
        output_file.parent.mkdir(parents=True, exist_ok=True)

        with open(output_file, 'w', encoding='utf-8') as f:
            # Netscape HTTP Cookie File 헤더
            f.write("# Netscape HTTP Cookie File\n")
            f.write("# This file was generated by Douyin Cookie Extractor\n")
            f.write("# Edit at your own risk.\n\n")

            for cookie in cookies:
                domain = cookie.get('domain', '')
                flag = 'TRUE' if domain.startswith('.') else 'FALSE'
                path = cookie.get('path', '/')
                secure = 'TRUE' if cookie.get('secure', False) else 'FALSE'
                expiration = str(int(cookie.get('expiry', 0))) if 'expiry' in cookie else '0'
                name = cookie.get('name', '')
                value = cookie.get('value', '')

                # Netscape 형식: domain flag path secure expiration name value
                f.write(f"{domain}\t{flag}\t{path}\t{secure}\t{expiration}\t{name}\t{value}\n")

        print(f"✅ 쿠키 저장 완료: {output_file}")
        print(f"📊 총 {len(cookies)}개의 쿠키 저장됨")
        print()
        print("=" * 80)
        print("🎉 쿠키 추출 성공!")
        print("=" * 80)
        print()
        print("💡 이제 Douyin 영상을 다운로드할 수 있습니다!")
        print()

        return True

    except Exception as e:
        print(f"\n❌ 오류 발생: {e}")
        import traceback
        traceback.print_exc()
        return False

    finally:
        print("🔒 브라우저 종료 중...")
        driver.quit()
        print("✅ 완료!")


def main():
    """메인 함수"""
    # 쿠키 저장 경로
    output_file = Path(__file__).parent.parent.parent / "douyin_downloads" / "cookies.txt"

    print()
    print("📍 쿠키 저장 경로:", output_file)
    print()

    # 쿠키 추출
    success = extract_douyin_cookies(output_file)

    if success:
        print("\n✅ 쿠키 추출이 완료되었습니다!")
        print(f"📁 파일 위치: {output_file}")
        print()
        print("🎬 이제 Douyin 영상을 다운로드해보세요!")
    else:
        print("\n❌ 쿠키 추출에 실패했습니다.")
        print("💡 다시 시도하거나, 수동으로 쿠키를 추출해주세요.")


if __name__ == "__main__":
    main()
